function Figure3
%% Figure3 - Exploratory CW asymptotic diagnostics
%
% Authors: Andre Liemert (ILM-ULM)
%          Lorenzo Pattelli (INRIM)
%          Fabrizio Martelli (UNIFI)
% License: MIT
%
% Description:
%   Candidate visualizations for the CW asymptotic mismatch theorem.
%   The figures are intentionally split into small conceptual groups rather
%   than a single crowded multi-panel layout. They visualize the two independent
%   CW matching conditions (pole location and residue), the complex-pole picture,
%   the exact isotropic fine structure, and high-albedo anisotropic trends.
%
% Dependencies:
%   - data/a_values.mat
%   - utils/cw_iso_asymptotics.m
%   - utils/HG_high_albedo_coeffs.m
%   - Octave's built-in viridis colormap

  %% Load pre-computed CW convergence database
  baseDir = fileparts(mfilename('fullpath'));
  rootDir = fileparts(baseDir);
  dataDir = fullfile(rootDir, 'data');
  load(fullfile(dataDir, 'a_values.mat'));  % g_vals, mua_vals, mus_reduced, best_a_matrix, avg_ratio_matrix

  eta_vals = mua_vals ./ mus_reduced;        % eta = mua / mu_s'
  g_pick = [0, 0.5, 0.9, 0.99];
  g_idx = nearest_indices(g_vals, g_pick);
  g_colors = viridis(numel(g_idx));

  %% Figure 3a - Pole/residue compatibility map, several absorption levels
  plot_matching_space_2d;

  %% Figure 3b - Same compatibility map lifted to a as third coordinate
  plot_matching_space_3d;

  %% Figure 3c - Zero-contour map in the (rho,a) plane
  plot_no_common_zero_map;

  %% Figure 3d-e - Complex-pole picture and unrolled imaginary-axis trajectories
  plot_complex_pole_trajectories;

  %% Figure 3f-g - Exact isotropic fine structure and amplitude defect
  plot_isotropic_fine_structure(eta_vals, best_a_matrix, avg_ratio_matrix, g_idx);

  %% Figure 3h-i - Anisotropic high-albedo checks from the numerical database
  plot_anisotropic_high_albedo(eta_vals, g_vals, g_idx, g_colors, best_a_matrix, avg_ratio_matrix);

  %% Figure 3j - Anisotropic pole shift inferred from the exponent-matched database
  plot_anisotropic_pole_shift(eta_vals, g_vals, g_idx, g_colors, mus_reduced, mua_vals, best_a_matrix);
end


function plot_matching_space_2d
% PLOT_MATCHING_SPACE_2D - Map one scalar a into the two independent CW conditions.
%
% The target point (1,1) would require simultaneous agreement of the pole
% position mu_eff=nu_1 and the residue A_1D=1. Each curve is generated by
% sweeping a for one absorption ratio rho=mua/mus.

  rho_set = [1e-3, 1e-2, 1e-1];
  mus = 1;
  a_grid = linspace(-2.0, 2.0, 401);
  colors = viridis(numel(rho_set));

  figure
  hold on
  title('Figure 3a: two CW matching conditions cannot be met simultaneously')
  for i = 1:numel(rho_set)
    rho = rho_set(i);
    [x_decay, y_residue, a_decay, R_decay, a_residue, x_residue] = matching_curve_iso(rho, mus, a_grid);

    plot(x_decay, y_residue, '-', 'Color', colors(i,:), 'LineWidth', 1.8, ...
         'DisplayName', sprintf('\\mu_a/\\mu_s = %.3g', rho))
    plot(1, R_decay, 'o', 'MarkerFaceColor', colors(i,:), 'MarkerEdgeColor', 'k', ...
         'HandleVisibility', 'off')
    plot(x_residue, 1, 's', 'MarkerFaceColor', colors(i,:), 'MarkerEdgeColor', 'k', ...
         'HandleVisibility', 'off')

    if rho == 1e-1
      text(1.002, R_decay, sprintf('  a_{decay}=%.9f', a_decay))
      text(x_residue, 1.002, sprintf('  a_{res}=%.3f', a_residue))
    end
  end

  plot(1, 1, 'kp', 'MarkerFaceColor', 'k', 'MarkerSize', 10, 'HandleVisibility', 'off')
  draw_target_cross;
  xlabel('\mu_{eff}/\nu_1')
  ylabel('A_1 D(a)')
  legend('location', 'southwest')
  grid on
  box on
  hold off
end


function plot_matching_space_3d
% PLOT_MATCHING_SPACE_3D - Super-charged pole/residue map with a as vertical axis.
%
% The vertical black line marks the locus where both matching conditions would
% be satisfied for some value of a. The colored trajectories miss this line.

  rho_set = [1e-3, 1e-2, 1e-1];
  mus = 1;
  a_grid = linspace(-2.0, 2.0, 401);
  colors = viridis(numel(rho_set));

  figure
  hold on
  title('Figure 3b: compatibility trajectories in (pole,residue,a) space')
  for i = 1:numel(rho_set)
    rho = rho_set(i);
    [x_decay, y_residue, a_decay, R_decay, a_residue, x_residue] = matching_curve_iso(rho, mus, a_grid);

    plot3(x_decay, y_residue, a_grid, '-', 'Color', colors(i,:), 'LineWidth', 1.8, ...
          'DisplayName', sprintf('\\rho = %.3g', rho))
    plot3(1, R_decay, a_decay, 'o', 'MarkerFaceColor', colors(i,:), 'MarkerEdgeColor', 'k', ...
          'HandleVisibility', 'off')
    plot3(x_residue, 1, a_residue, 's', 'MarkerFaceColor', colors(i,:), 'MarkerEdgeColor', 'k', ...
          'HandleVisibility', 'off')
  end

  a_target = [a_grid(1), a_grid(end)];
  plot3([1 1], [1 1], a_target, 'k--', 'LineWidth', 1.2, 'HandleVisibility', 'off')
  plot3(1, 1, 0.2, 'kp', 'MarkerFaceColor', 'k', 'MarkerSize', 10, 'HandleVisibility', 'off')
  xlabel('\mu_{eff}/\nu_1')
  ylabel('A_1 D(a)')
  zlabel('a')
  legend('location', 'northeast')
  view(45, 22)
  grid on
  box on
  hold off
end


function plot_no_common_zero_map
% PLOT_NO_COMMON_ZERO_MAP - Show the two zero conditions in the (rho,a) plane.
%
% The decay-matching condition produces a=a_decay(rho). The residue-matching
% condition produces a=a_res(rho). Exact CW diffusion would require their
% intersection. They meet only in the singular limit rho->0.

  mus = 1;
  rho_vec = logspace(-5, 0, 501);
  [~, a_decay, R_decay, ~, A1] = cw_iso_asymptotics(rho_vec, mus*ones(size(rho_vec)));
  a_residue = (A1 ./ 3 - mus) ./ (rho_vec .* mus);

  % A soft background: log10 of the combined mismatch at each (rho,a).
  % A1 and nu1 depend on rho only, so compute them once and replicate.
  a_grid = linspace(-0.25, 0.8, 281);
  [RHO, A] = meshgrid(rho_vec, a_grid);
  A1_grid  = repmat(A1, numel(a_grid), 1);
  nu1_grid = repmat(nu1_from_rho(rho_vec, mus), numel(a_grid), 1);
  D_grid = 1 ./ (3 .* (mus + A .* RHO .* mus));
  mu_eff_grid = sqrt(RHO .* mus ./ D_grid);
  decay_mismatch = mu_eff_grid ./ nu1_grid - 1;
  residue_mismatch = A1_grid .* D_grid - 1;
  combined = sqrt(decay_mismatch.^2 + residue_mismatch.^2);
  combined = max(combined, eps);

  figure
  imagesc(log10(rho_vec), a_grid, log10(combined))
  set(gca, 'YDir', 'normal')
  colormap(viridis(256))
  colorbar
  hold on
  plot(log10(rho_vec), a_decay, 'w-', 'LineWidth', 2.0, 'DisplayName', 'decay match')
  plot(log10(rho_vec), a_residue, 'w--', 'LineWidth', 2.0, 'DisplayName', 'residue match')
  plot(log10(rho_vec), 1/5*ones(size(rho_vec)), ':', 'Color', [0.8 0.8 0.8], 'HandleVisibility', 'off')
  xlabel('log_{10}(\mu_a/\mu_s)')
  ylabel('a')
  title('Figure 3c: no common zero of decay and residue mismatch')
  legend('location', 'southwest')
  box on
  hold off
end


function plot_complex_pole_trajectories
% PLOT_COMPLEX_POLE_TRAJECTORIES - Visualize poles in the complex k-plane.
%
% For real positive optical coefficients in the infinite isotropic medium, the
% relevant poles are purely imaginary. The left panel shows this collapse onto
% the imaginary axis; the right panel unwraps that axis as a function of rho.

  rho_vec = logspace(-5, 0.8, 501);
  mus = 1;
  [lambda, a_star, ~, ~, ~, nu1] = cw_iso_asymptotics(rho_vec, mus*ones(size(rho_vec)));
  k_rte = 1i .* nu1 ./ mus;
  k_branch = 1i .* (1 + rho_vec);       % continuous-spectrum threshold, normalized by mu_s

  a_fixed = [0, 1/5, 1/3, 1];
  colors = viridis(numel(a_fixed));

  figure

  subplot(1,2,1)
  hold on
  scatter(real(k_branch), imag(k_branch), 18, log10(rho_vec), 'filled', ...
          'DisplayName', 'branch point i\mu_t')
  scatter(real(k_rte), imag(k_rte), 18, log10(rho_vec), 'filled', ...
          'MarkerEdgeColor', 'k', 'DisplayName', 'RTE pole i\nu_1')
  plot([0 0], [0 max(imag(k_branch))], 'k:', 'HandleVisibility', 'off')
  colormap(viridis(256))
  colorbar
  xlabel('Re(k/\mu_s)')
  ylabel('Im(k/\mu_s)')
  title('Figure 3d: poles lie on the imaginary k-axis')
  legend('location', 'northwest')
  axis tight
  grid on
  box on
  hold off

  subplot(1,2,2)
  hold on
  semilogx(rho_vec, imag(k_branch), 'k:', 'LineWidth', 1.5, 'DisplayName', 'branch point \mu_t')
  semilogx(rho_vec, imag(k_rte), 'k-', 'LineWidth', 2.0, 'DisplayName', 'RTE pole \nu_1')
  for i = 1:numel(a_fixed)
    a = a_fixed(i);
    k_de = sqrt(3 .* rho_vec .* (1 + a .* rho_vec));
    semilogx(rho_vec, k_de, '--', 'Color', colors(i,:), 'LineWidth', 1.5, ...
             'DisplayName', sprintf('DE pole, a = %.3g', a))
  end
  semilogx(rho_vec, imag(k_rte), '-', 'Color', [0 0 0], 'LineWidth', 2.2, 'HandleVisibility', 'off')
  xlabel('\mu_a/\mu_s')
  ylabel('imaginary pole position / \mu_s')
  title('Figure 3e: unwrapped pole trajectories')
  legend('location', 'northwest')
  grid on
  box on
  hold off
end


function plot_isotropic_fine_structure(eta_vals, best_a_matrix, avg_ratio_matrix, g_idx)
% PLOT_ISOTROPIC_FINE_STRUCTURE - Exact isotropic a_star and amplitude mismatch.

  rho_vec = logspace(-5, 0, 401);
  [~, a_exact, R_exact] = cw_iso_asymptotics(rho_vec, ones(size(rho_vec)));
  a_series = iso_a_series_rho(rho_vec);
  mismatch_exact = 1 - R_exact;
  mismatch_lead = (4/5) .* rho_vec;

  rho0 = 1e-2;
  [~, a0, R0] = cw_iso_asymptotics(rho0, 1);

  figure

  subplot(1,2,1)
  hold on
  semilogx(rho_vec, a_exact, '-', 'LineWidth', 1.8, 'DisplayName', 'exact pole')
  semilogx(rho_vec, a_series, '--', 'LineWidth', 1.4, 'DisplayName', 'series')
  semilogx(eta_vals, best_a_matrix(g_idx(1),:), 'o', 'MarkerSize', 3, 'DisplayName', 'numeric extraction')
  plot(rho0, a0, 'p', 'MarkerFaceColor', 'k', 'MarkerEdgeColor', 'k', 'HandleVisibility', 'off')
  text(rho0*1.15, a0, sprintf('%.9f', a0))
  xlabel('\mu_a/\mu_s')
  ylabel('a_*')
  title('Figure 3f: isotropic fine structure')
  legend('location', 'northwest')
  grid on
  box on
  hold off

  subplot(1,2,2)
  hold on
  loglog(rho_vec, mismatch_exact, '-', 'LineWidth', 1.8, 'DisplayName', 'exact')
  loglog(rho_vec, mismatch_lead, '--', 'LineWidth', 1.4, 'DisplayName', '4\mu_a/(5\mu_s)')
  loglog(eta_vals, 1 - avg_ratio_matrix(g_idx(1),:), 'o', 'MarkerSize', 3, 'DisplayName', 'numeric extraction')
  plot(rho0, 1-R0, 'p', 'MarkerFaceColor', 'k', 'MarkerEdgeColor', 'k', 'HandleVisibility', 'off')
  xlabel('\mu_a/\mu_s')
  ylabel('1 - lim \phi/\psi')
  title('Figure 3g: isotropic amplitude defect')
  legend('location', 'southeast')
  grid on
  box on
  hold off
end


function plot_anisotropic_high_albedo(eta_vals, g_vals, g_idx, colors, best_a_matrix, avg_ratio_matrix)
% PLOT_ANISOTROPIC_HIGH_ALBEDO - Numerical approach to high-albedo slopes.

  figure

  subplot(1,2,1)
  hold on
  for k = 1:numel(g_idx)
    g = g_vals(g_idx(k));
    [~, ~, slope_R] = HG_high_albedo_coeffs(g);
    coeff_data = (1 - avg_ratio_matrix(g_idx(k),:)) ./ eta_vals;
    semilogx(eta_vals, coeff_data, '-', 'Color', colors(k,:), 'LineWidth', 1.5, ...
             'DisplayName', sprintf('g = %.2g', g))
    line([eta_vals(1), eta_vals(end)], [slope_R, slope_R], ...
         'LineStyle', '--', 'Color', colors(k,:), 'HandleVisibility', 'off')
  end
  xlim([eta_vals(1), 1e-1])
  ylim([0.35, 0.85])
  xlabel('\eta = \mu_a/\mu_s''')
  ylabel('(1 - lim \phi/\psi) / \eta')
  title('Figure 3h: high-albedo residue slope')
  legend('location', 'northeast')
  grid on
  box on
  hold off

  subplot(1,2,2)
  hold on
  for k = 1:numel(g_idx)
    g = g_vals(g_idx(k));
    [a0, a1] = HG_high_albedo_coeffs(g);
    coeff_data = (best_a_matrix(g_idx(k),:) - a0) ./ eta_vals;
    semilogx(eta_vals, coeff_data, '-', 'Color', colors(k,:), 'LineWidth', 1.5, ...
             'DisplayName', sprintf('g = %.2g', g))
    line([eta_vals(1), eta_vals(end)], [a1, a1], ...
         'LineStyle', '--', 'Color', colors(k,:), 'HandleVisibility', 'off')
  end
  xlim([eta_vals(1), 1e-1])
  ylim([-0.11, 0.04])
  xlabel('\eta = \mu_a/\mu_s''')
  ylabel('(a_* - a_0) / \eta')
  title('Figure 3i: Holte first correction')
  legend('location', 'southwest')
  grid on
  box on
  hold off
end


function plot_anisotropic_pole_shift(eta_vals, g_vals, g_idx, colors, mus_reduced, mua_vals, best_a_matrix)
% PLOT_ANISOTROPIC_POLE_SHIFT - Pole shift inferred from exponent-matched a.
%
% Since the database a_* is obtained by stabilizing the far-field ratio, the
% corresponding RTE pole can be reconstructed as nu_1 = sqrt(mu_a/D_*). This
% panel shows how anisotropy modifies the pole relative to the classical
% diffusion pole sqrt(3 mu_a mu_s').

  figure
  hold on
  for k = 1:numel(g_idx)
    g = g_vals(g_idx(k));
    a_star = best_a_matrix(g_idx(k),:);
    nu_ratio = sqrt(1 + a_star .* eta_vals);  % nu_1 / sqrt(3 mua mu_s')
    [a0] = HG_high_albedo_coeffs(g);
    lead = 1 + 0.5 .* a0 .* eta_vals;

    semilogx(eta_vals, nu_ratio, '-', 'Color', colors(k,:), 'LineWidth', 1.6, ...
             'DisplayName', sprintf('g = %.2g', g))
    semilogx(eta_vals, lead, '--', 'Color', colors(k,:), 'LineWidth', 1.2, ...
             'HandleVisibility', 'off')
  end
  xlim([eta_vals(1), 1e-1])
  xlabel('\eta = \mu_a/\mu_s''')
  ylabel('\nu_1 / \sqrt{3\mu_a\mu_s''}')
  title('Figure 3j: anisotropic pole shift from the matched database')
  legend('location', 'northwest')
  grid on
  box on
  hold off
end


function [x_decay, y_residue, a_decay, R_decay, a_residue, x_residue] = matching_curve_iso(rho, mus, a_grid)
% MATCHING_CURVE_ISO - Compute the 2D pole/residue trajectory for fixed rho.

  mua = rho * mus;
  [~, a_decay, R_decay, ~, A1, nu1] = cw_iso_asymptotics(mua, mus);

  denom = mus + a_grid .* mua;
  valid = denom > 0;
  D_grid = nan(size(a_grid));
  D_grid(valid) = 1 ./ (3 .* denom(valid));

  x_decay = sqrt(mua ./ D_grid) ./ nu1;
  y_residue = A1 .* D_grid;

  a_residue = (A1 / 3 - mus) / mua;
  D_residue = 1 / A1;
  x_residue = sqrt(mua / D_residue) / nu1;
end


function draw_target_cross
% DRAW_TARGET_CROSS - Draw dashed guide lines through the perfect-match point.
  xl = xlim;
  yl = ylim;
  line([1 1], yl, 'LineStyle', '--', 'Color', [0.4 0.4 0.4], 'HandleVisibility', 'off')
  line(xl, [1 1], 'LineStyle', '--', 'Color', [0.4 0.4 0.4], 'HandleVisibility', 'off')
  xlim(xl)
  ylim(yl)
end



function nu1 = nu1_from_rho(rho, mus)
% NU1_FROM_RHO - Isotropic RTE pole location for rho=mua/mus.
  mua = rho .* mus;
  [~, ~, ~, ~, ~, nu1] = cw_iso_asymptotics(mua, mus*ones(size(rho)));
end


function idx = nearest_indices(grid, values)
% NEAREST_INDICES - Return indices of grid points nearest to requested values.
  idx = zeros(size(values));
  for k = 1:numel(values)
    [~, idx(k)] = min(abs(grid - values(k)));
  end
end


function a = iso_a_series_rho(rho)
% ISO_A_SERIES_RHO - High-albedo isotropic series for a_star in rho=mua/mus.
  a = 1/5 + (4/175).*rho ...
      - (144/336875).*rho.^3 ...
      - (576/21896875).*rho.^4 ...
      + (10368/766390625).*rho.^5;
end
